// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAtfV9Yb_JgQPuSbl827LcWgbbxAh1JDjg',
    appId: '1:380449950010:web:3c2e7f993ca563ba45a803',
    messagingSenderId: '380449950010',
    projectId: 'flutterapp-f4cdc',
    authDomain: 'flutterapp-f4cdc.firebaseapp.com',
    storageBucket: 'flutterapp-f4cdc.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyB6gZzNDLWiLs5c7XWU3aiNTCi2va3QhWE',
    appId: '1:380449950010:android:b8725d2921233d8a45a803',
    messagingSenderId: '380449950010',
    projectId: 'flutterapp-f4cdc',
    storageBucket: 'flutterapp-f4cdc.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBkMGkUyNLBXxSVhZxQEY9HqKU0YYe1qfY',
    appId: '1:380449950010:ios:1d6d8569d5b9adbb45a803',
    messagingSenderId: '380449950010',
    projectId: 'flutterapp-f4cdc',
    storageBucket: 'flutterapp-f4cdc.appspot.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBkMGkUyNLBXxSVhZxQEY9HqKU0YYe1qfY',
    appId: '1:380449950010:ios:d20b07aa5661907045a803',
    messagingSenderId: '380449950010',
    projectId: 'flutterapp-f4cdc',
    storageBucket: 'flutterapp-f4cdc.appspot.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
